services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - quickfood-network

  delivery-service:
    build: ./delivery-service
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - quickfood-network

  menu-service:
    build: ./menu-service
    ports:
      - "5003:5003"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - quickfood-network

  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - quickfood-network

  order-service:
    build: ./order-service
    ports:
      - "5005:5005"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - quickfood-network

  payment-service:
    build: ./payment-service
    ports:
      - "5006:5006"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - quickfood-network

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "5007:5007"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - quickfood-network

volumes:
  mongodb_data:

networks:
  quickfood-network:
    driver: bridge
