version: "3"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
  
  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    env_file:
      - .env

  delivery-service:
    build: ./delivery-service
    ports:
      - "5002:5002"
    env_file:
      - .env

  menu-service:
    build: ./menu-service
    ports:
      - "5003:5003"
    env_file:
      - .env

  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"
    env_file:
      - .env
  
  order-service:
    build: ./order-service
    ports:
      - "5005:5005"
    env_file:
      - .env
  
  payment-service:
    build: ./payment-service
    ports:
      - "5006:5006"
    env_file:
      - .env

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "5007:5007"
    env_file:
      - .env
